name: pillsoclock
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  flutter_local_notifications: ^19.5.0
  fluttertoast: ^9.0.0
  intl: ^0.20.2
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_maps_flutter: ^2.13.1
  uuid: ^4.5.1
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  android_intent_plus: ^6.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/icon1.png
    - assets/carga1.gif
    
flutter_icons:
  android: true
  ios: true
  image_path: assets/icon1.png
  adaptive_icon_background: "#FFFFFF"




